const SETCONTRACT = 'SETCONTRACT';
const SETCONTRACTSTATUS = 'SETCONTRACTSTATUS';
const SETCONTRACTLINK = 'SETCONTRACTLINK';
const SETCONTRACTHANDLERSTATE = 'SETCONTRACTHANDLERSTATE';
const SETCONTRACTCOLLECTIONS = 'SETCONTRACTCOLLECTIONS';
const SETCONTRACTTEMPLATES = 'SETCONTRACTTEMPLATES';
const SETCONTRACTCONTACTS = 'SETCONTRACTCONTACTS';
const SETSTATUSDATA = 'SETSTATUSDATA';
const SETPARTICIPANTS = 'SETPARTICIPANTS';
const SETOPPORTUNITYPRODUCTS = 'SETOPPORTUNITYPRODUCTS';

export {
  SETCONTRACT,
  SETCONTRACTLINK,
  SETCONTRACTSTATUS,
  SETCONTRACTHANDLERSTATE,
  SETCONTRACTCOLLECTIONS,
  SETCONTRACTTEMPLATES,
  SETCONTRACTCONTACTS,
  SETSTATUSDATA,
  SETPARTICIPANTS,
  SETOPPORTUNITYPRODUCTS,
};
