export const styles = {
  popupContainer: {
    background: 'rgba(0,0,0,0.3)',
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  popup: {
    width: '720px',
    height: '790px',
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%,-50%)',
    background: 'white',
    padding: '18px',
    fontFamily: "'Roboto', sans-serif",
    color: 'black',
    boxShadow:
      '0px 2px 2px rgba(0, 0, 0, 0.24), 0px 0px 2px rgba(0, 0, 0, 0.12)',
  },
  closeBtn: {
    position: 'absolute',
    top: '20px',
    right: '20px',
    fontSize: '20px',
    cursor: 'pointer',
  },
  title: {
    fontWeight: 600,
    fontSize: '24px',
    letterSpacing: '0.05em',
    color: '#353535',
    paddingBottom: '8px',
    borderBottom: '1px solid #CFCDCC',
  },
  select: {
    width: '240px',
    height: '40px',
    fontSize: '16px',
    letterSpacing: '0.05em',
    color: 'black',
    border: '1px  solid #D2D2D2',
    borderRadius: '3px',
    background: 'white',
  },
  inputContainer: {
    width: '100%',
    height: '75px',
    border: '1px dashed #D2D2D2',
    borderRadius: '4px',
    cursor: 'pointer',
    position: 'relative',
  },
  fileInput: {
    top: 0,
    left: 0,
    position: 'absolute',
    height: '100%',
    width: '100%',
    opacity: 0,
    cursor: 'pointer',
    zIndex: 1,
  },
  inputTitle: {
    transform: 'translate(-50%,-50%)',
    top: '50%',
    left: '50%',
    position: 'absolute',
    fontSize: '16px',
    letterSpacing: '0.05em',
    display: 'flex',
    alignItems: 'center',
  },
  section: {
    borderBottom: '1px solid #CFCDCC',
  },
  sectionTitle: {
    fontSize: '24px',
    lineHeight: '28px',
    letterSpacing: '0.05em',
    marginTop: '8px',
    marginBottom: '8px',
  },
  sectionContainer: {
    height: '180px',
    overflow: 'scroll',
  },
  attachmentSection: {
    height: '140px',
  },
  actionBtn: {
    color: 'white',
    background: '#3e4658',
    boxShadow:
      '0px 2px 2px rgba(0, 0, 0, 0.24), 0px 0px 2px rgba(0, 0, 0, 0.12)',
    borderRadius: '2px',
    marginTop: '30px',
    marginBottom: '15px',
    fontWeight: '500',
    fontSize: '14px',
    letterSpacing: '0.0357143em',
    height: '36px',
    textTransform: 'none',
    border: 'none',
    width: '160px',
  },
  disabledBtn: {
    color: 'white',
    background: '#d0cecd',
    boxShadow:
      '0px 2px 2px rgba(0, 0, 0, 0.24), 0px 0px 2px rgba(0, 0, 0, 0.12)',
    borderRadius: '2px',
    marginTop: '30px',
    marginBottom: '15px',
    fontWeight: '500',
    fontSize: '14px',
    letterSpacing: '0.0357143em',
    height: '36px',
    textTransform: 'none',
    border: 'none',
    width: '160px',
    pointer: 'none',
  },
  itemContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    minHeight: '85px',
  },
  attachmentContainer: {
    minHeight: '65px',
  },
  checkbox: {
    marginRight: '20px',
  },
  itemData: {
    display: 'flex',
    alignItems: 'center',
    width: '70%',
    marginRight: '20px',
  },
  contactData: {
    fontSize: '16px',
    letterSpacing: '0.05em',
    lineHeight: '19px',
    color: 'black',
  },
  contact: {
    fontWeight: 600,
  },
  attachmentName: {
    fontSize: '16px',
    lineHeight: '19px',
    letterSpacing: '0.05em',
    textDecoration: 'underline',
  },
  btnContainer: {
    display: 'flex',
    width: '100%',
    justifyContent: 'center',
  },
  errorContainer: {
    display: 'flex',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-around',
    height: '100px',
  },
  error: {
    fontSize: '15px',
    lineHeight: '18px',
    letterSpacing: '0.05em',
    color: 'black',
    width: '92%',
  },
  footerLogo: {
    position: 'absolute',
    color: 'black',
    fontSize: '14px',
    lineHeight: '16px',
    letterSpacing: '0.05em',
    bottom: '10px',
    right: '15px',
  },
  svg: {
    marginRight: '8px',
  },
};
